#! /bin/bash
# Author: Bruno de Lima e Silva (brunodles) <dlimaun@gmail.com>

# Check root user
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo "Add PPA"
sudo add-apt-repository -y ppa:graphics-drivers/ppa
sudo apt-get -qq update

echo "Install intel-microcode and cpu-checker"
echo " - This is useful for the emulator"
sudo apt install intel-microcode cpu-checker

echo "Install some helpers"
sudo apt-get -y -qq install software-properties-common python-software-properties

echo "Install Java"
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
sudo apt-get -y -qq install oracle-java8-installer
sudo apt-get -y -qq install oracle-java8-set-default
update-java-alternatives -s java-8-oracle
echo "JAVA_HOME=/usr/lib/jvm/java-8-oracle">>/etc/environment
